name: Java Workflow Demo

on: [push]

jobs:
  BuildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List the files in current directory
        run: ls ${{github.workspace}}
      - name: Verify the Java Version
        run: java --version
      - name: Compile the Java Program
        run: javac hello.java
      - name: Verify Java Compiled or Not
        run: ls ${{github.workspace}}
      - name: Execute the Java Code
        run: java HelloWorld
